### ISSUE TITLE
ENV separator

### ISSUE THREAD

**Issue by odino** [namshi/reconfig#15]
@unlucio currently we split by `_` to inject environment variables in the config, but I ran through a case where I had a config like:

``` yaml
projects:
  nginx_pagespeed:
    something: something_else
```

As you understand the fact that the key `nginx_pagespeed` has an underscore kinda breaks our stuff, as you cant inject anything to that object. I think we could do something like wht symfony does (using `__`) or at least give the user a way to specify their preferred separator.
